name: Build Container
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v6
      -
        name: Login docker registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Check repository
        run: ls -lap
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          target: dev
          tags: ghcr.io/jaster-prj/devcontainer-zephyr-dev:latest
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          target: workspace
          tags: ghcr.io/jaster-prj/devcontainer-zephyr-workspace:latest
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          target: zephyr
          tags: ghcr.io/jaster-prj/devcontainer-zephyr:latest
      -
        name: Logout docker registry
        run: docker logout ghcr.io